application: optical-carrier-146721
version: 2
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- channel_presence

handlers:
- url: /.*
  script: main.app
- url: /static
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
